### ISSUE TITLE
Nexus data with detectorgroup needed

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#125]
We currently offer support for multiple detectors (in one detector group) in Nexus files. I have no idea if this works, as it is not covered by any tests: https://codecov.io/gh/dials/dxtbx/src/master/format/FormatNexus.py#L76

Can we have a test file? If not we should consider removing the code, as the lack of testing is blocking the work on #122.

**Comment by phyy-nx** [comment]
Hi, the JF16M uses this feature.  See #93.

**Comment by Anthchirp** [comment]
Very useful, thank you!
