### ISSUE TITLE
Document rotation operator convention of the goniometer object

### ISSUE THREAD

**Issue by benjaminhwilliams** [cctbx/dxtbx#128]
The convention adopted for the rotation operator methods of the goniometer object is only documented [here](https://github.com/cctbx/dxtbx/blob/30adeb41d667be96ba7208251bd1869991c1008e/model/goniometer.h#L35-L57).  It's not clear to non-authors of the code what the following methods refer to:
 - `get_angles`,
 - `get_axes`,
 - `get_fixed_rotation`,
 - `get_names`,
 - `get_num_scan_points`,
 - `get_rotation_axis`,
 - `get_rotation_axis_datum`,
 - `get_scan_axis`,
 - `get_setting_rotation`,
 - `get_setting_rotation_at_scan_point`,
 - `get_setting_rotation_at_scan_points`.

Could this be better documented?

**Comment by benjaminhwilliams** [comment]
Now that I understand this, I have written this up, but don't know where it should go.  How do we document dxtbx?

**Comment by rjgildea** [comment]
dxtbx documentation is generated alongside the dials documentation:
https://dials.github.io/documentation/library_reference/dxtbx/goniometer.html
https://github.com/dials/dials/tree/master/doc/sphinx/documentation/library_reference/dxtbx

**Comment by elena-pascal** [comment]
Did this knowledge end up anywhere? I also want to know rotation convention and reference frames for all the used vectors.
