### ISSUE TITLE
FormatCBFFull broken by recent pycbf api change (P3 only?)

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#131]
I think this commit:

https://github.com/yayahjb/cbflib/commit/972881d6359582b9fadd683ff38620d90a879a77

At

https://github.com/yayahjb/cbflib/commit/972881d6359582b9fadd683ff38620d90a879a77#diff-5b08a0b1c5da64ec11dc7787fd02f55aL3285

broke dxtbx - at least on Python 3 - running side-by-side tests now. Error is ```TypeError: in method 'cbf_handle_struct_read_widefile', argument 2 of type 'char *'```

**Comment by graeme-winter** [comment]
Dropped HJB a line...

**Comment by Anthchirp** [comment]
suspect smoking gun is:
![image](https://user-images.githubusercontent.com/2102431/71713780-1593aa80-2e03-11ea-92ed-673b391daa20.png)

SWIG 3.0.0 (2014-03-16) "completed" the support for Python 3.3.

Suggest that neither 2.0.12 (2014-02-09) nor 3.0.10 (2016-06-12) are really appropriate. 4.0.1 (2019-08-21 and latest release) supports 2.7, 3.2-3.8.

**Comment by graeme-winter** [comment]
@Anthchirp 👍 thanks!

**Comment by graeme-winter** [comment]
Verified - recompiled swig with 3.0.12 (which I had lying around) and it was fine - I do not however have permission to push the updated version.

**Comment by graeme-winter** [comment]
Fixed by https://github.com/yayahjb/cbflib/commit/f63e736e7a7514b3c9c89ba372790fc1aabd5491
