### ISSUE TITLE
dxtbx.image_average doesn't support gain

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#148]
dxtbx.image_average writes a cbf for the average image, but gain is lost in this cbf.  This leads to problems when using it to compute a reference geometry as the wrong gain is propagated into the refined geometry.

How to reproduce:
```
$ cd dials_regression/image_examples/SACLA_MPCCD_Cheetah
$ dials.show run266702-0-subset.h5 | grep gain
  gain: 10
$ dxtbx.image_average run266702-0-subset.h5 -v -a avg.cbf
$ dials.show avg.cbf | grep gain
  gain: 1
```

**Comment by graeme-winter** [comment]
Known thing that the gain will be modified by the process anyway, right? I mean beyond the administrative bug that the gain value is misplaced, the resulting gain in the image will be reduced if averaging occurs.

**Comment by phyy-nx** [comment]
Sure, not really the scope I'm worrying about though.  We aren't using averages to do any signal modeling, just to get the beam center and distance from powder.

**Comment by rjgildea** [comment]
> when using it to compute a reference geometry as the wrong gain is propagated into the refined geometry.

Perhaps the gain _shouldn't_ be propagated when using a reference geometry, as the **gain** isn't strictly anything to do with the **geometry**?

**Comment by phyy-nx** [comment]
Oh, that's a good point.  Right now I'm using the reference detector as provided in dials.stills_process but instead I could sync the panel positions...

(See https://github.com/dials/dials/blob/master/command_line/stills_process.py#L480-L488)
