### ISSUE TITLE
dxtbx Format stack should not assume data are in files

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#162]
The current stack assumes that the data are in files or file-like locations - if however the data for analysis are in an object store there is no way to retrofit this at the moment, because the discovery process assumes `open()` is a thing. 

Will need to add a fork at the top of the class hierarchy which asks whether the `Format` object is a `FormatFile` (i.e. the current implementation) or some other data source. Bonus points for figuring out how to decouple - 

 - the data source
 - the file format 
 - the detector type

i.e. at the moment the detector type is coupled strongly to the file format (which is reasonable, looking at history) however it would be valid but unsupported to have Eiger data in SMV format, or an object store or 0mq stream which sends in data as raw byte arrays with metadata as a parallel service. 

Some very preliminary exploratory work went into https://github.com/cctbx/dxtbx/tree/data-not-files - this should be considered as nothing more than a mapping exercise. 

Use case applies to FELs as well as synchrotron I am certain. Would like to gather requirements on that here / in a shared area so we can figure out how to do this. 

Science case: if we want to analyse data on the fly without ever sending it to disk we need to do something sane like this. N.B. not intending to keep the data in RAM for this, have to assume it is too large for that.

**Comment by phyy-nx** [comment]
FWIW I've been creating CBFs in memory and using them in dxtbx for a long time now:
https://github.com/cctbx/dxtbx/blob/master/format/FormatCBFCspad.py#L213

I do this using the MemReader functionality:
https://github.com/cctbx/dxtbx/blob/master/imageset.py#L36
https://github.com/cctbx/cctbx_project/blob/master/xfel/command_line/xtc_process.py#L1104

Essentially I create a cbf handle, pass it to the FormatCBFFullStillInMemory class constructor, put that in a MemReader and then create an ImageSet from it.  I can then do all the processing in memory without writing the CBF to disc.

**Comment by ndevenish** [comment]
I think this is more talking about a similar problem to XTC streams? e.g. I believe you currently create an extra file with the name of the stream and `find_format` that. Whereas being able to do something like:
```
$ dials.import xtc://exp=mfxo1916:run=20:smd
```
would be another way of solving the same problem (example from the format, sorry if this isn't a valid construct). I think it would definitely be a better fit for the things we have been talking about here.

The current model doesn't directly decouple the detector, format, file source, but I think is too embedded to change easily, and there are lots of abstraction-breaking behaviour around format instances, class caches etc. that are constraining our options in this area. I'd be happy to hear contradicting views on that, however. I think in most cases the detector model _is_ currently separate from the format, except for format-reader assumptions - and hopefully you could get this information from whatever service you are interrogating... Maybe you could support "point towards an object store and read whatever is inside" through some sort of MultiImage wrapper to other Format classes....

Anyway, my current strategy that I'm looking at this through is basically: 
- Make sure URL parameters make it through to the format registry `find` method
- Add a `scheme : List[str]` parameter to format classes that defaults to `["file"]`. Then, any classes that know about "more" can add the entries; and ones that don't support the current scheme will be skipped. In this case, `FormatXTC` could hypothetically just declare `scheme = ["file", "xtc"]` and have `xtc://` URLs passed directly to it (or existing file-based method).

I'm currently hoping that these steps will allow us to do most of what we want without being too intrusive.

I think treating as `FormatFile` and splitting off parallel format chains will just end up in spaghetti duplication and identical format logic split over multiple classes....

**Comment by phyy-nx** [comment]
For posterity, here's where we talked about doing FormatXTC as you mention before:
https://github.com/dials/dials/issues/335#issuecomment-362330514
