### ISSUE TITLE
Summit needs -fsigned-char

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#163]
Hi, [Summit](https://www.olcf.ornl.gov/summit/) has a set of compilers that has the default as unsigned char instead of signed char, something that is left up to the system in the C++ spec.  This causes reading mini cbfs to fail.  The solution is to add -fsigned-char to the dxtbx SConscript.  This should already be the default on most platforms, but will allow Summit to compile with fewer special flags.

Now, I tried this but it didn't work:
```
$ git diff
diff --git a/SConscript b/SConscript
index c7b298f..bacf6f4 100644
--- a/SConscript
+++ b/SConscript
@@ -101,6 +101,7 @@ if not env_etc.no_boost_python and hasattr(env_etc, "boost_adaptbx_include"):
     )

     env.Append(
+        CFLAGS='-fsigned-char',
         LIBS=env_etc.libm + ["cctbx", "scitbx_boost_python"] + env_etc.dxtbx_libs,
         LIBPATH=env_etc.dxtbx_lib_paths,
     )
```

This didn't not trigger a re-compile and if I delete a library to force it to compile the flag isn't added. 
 Any suggestions?

**Comment by phyy-nx** [comment]
Ok looks like CPPFLAGS works.  I've prepared a branch (signed_char) and will make a PR after its tested on Summit.

**Comment by ndevenish** [comment]
Can we fix this by being explicit about char type in the code where it is needed instead?

**Comment by Anthchirp** [comment]
The test introduces a dxtbx>dials dependency.

**Comment by Anthchirp** [comment]
(Also the test should really be a separate test function, not tested on all images and skipped on 99%)

**Comment by ndevenish** [comment]
> (Also the test should really be a separate test function, not tested on all images and skipped on 99%)
This "test" will also fail silently if the image is missing for some reason

**Comment by phyy-nx** [comment]
So, we looked at this.  There are over 1.5K instances where char is used in
cctbx_project without being typed as signed/unsigned:
find . -name "*.h" -o -name "*.cpp" | xargs grep -w char 2> /dev/null |
grep -v signed | wc -l

It would be super invasive to change them all to signed.

Right now we are leaning to adding -fsigned-char to the root libtbx
SConscript instead of dxtbx SConscript, but it's not locked in yet.

**Comment by phyy-nx** [comment]
I've dropped the dials dependency.  Feel free to do any other refactoring :)

**Comment by ndevenish** [comment]
Presumably every instance of the word "char" in the codebase isn't causing this issue; and even if so, changing the way dxtbx is built won't affect the instances in cctbx_project

**Comment by phyy-nx** [comment]
Ok so a bit more info.  @mewall has identified lines in cbflib_adaptbx to
be the culprit and not in dxtbx for this specific problem with minicbf.  So
if we add -fsigned-char anywhere it has to at least be to cbflib_adaptbx.
But, anywhere we are reading any kind of data using char buffers we could
have the same problem, so we don't know what other packages we need to add
the flag to.  That's why we are leaning toward adding -fsigned-char to the
libtbx SConscript where it will affect all packages.

**Comment by ndevenish** [comment]
So it's not the dxtbx build responsible and this issue can be closed?

**Comment by phyy-nx** [comment]
Not yet.  I'll close it when the Summit thing is totally resolved.  Thanks.

**Comment by Anthchirp** [comment]
I trust adding the flag to cbflib_adaptbx doesn't affect the global build (eg. dials etc.)?

Just a thing to consider: depending on specific compiler flags may not helpful in the long run if we want to move towards a `conda build` goal.

**Comment by phyy-nx** [comment]
Correct, adding it only to cbflib_adaptbx wouldn't affect any other package.

Regarding conda specific flags, it depends on the build recipe what happens and can be controlled by the package maintainers.

Talking more w/ @bkpoon, we want to try and fix the specific minicbf problem on summit in cbflib_adaptbx directly, so I'm closing this issue here.  Thanks all.
