### ISSUE TITLE
For format objects for multi panel detectors, provide method to give 2D representation

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#17]
i.e. if you want to show a picture, show results plotted as x, y or whatever for detectors which are made up from a collection of 2D panels, provide a mechanism to plot these on some larger 2D array.

See https://github.com/dials/dials/issues/575 for background

**Comment by dagewa** [comment]
I have code from another project that does a fast plane fit to points. Using that I could provide a method in `Format` that produces 2D fast, slow directions and correctly projected x, y pixel sizes for display of detectors that are mostly coplanar. Cases like I23 would have to do something different, of course. I can add this method if that sounds useful. It has a dependency on `numpy.linalg.svd` for the plane fit.

The current image viewer _does_ do something like this already, but I think it is rather image-viewer specific, whereas this would be something that lives in `Format` classes

**Comment by dagewa** [comment]
Actually we wouldn't explicitly need the projected pixel sizes if the function just reports the non-unit length 2D fast, slow vectors, and the 2D origin vector for each panel.

**Comment by rjgildea** [comment]
As I pointed out [above](https://github.com/cctbx/dxtbx/issues/17#issuecomment-398684723), we can use `panel.get_raw_image_offset()` to get the position of the panels in the underlying raw image array. This would work for the curved DLS I23 detector and for all Dectris Pilatus and Eiger detectors (i.e. most of the multi-panel detectors we are likely to care about here at DLS), and result in images that are consistent with what the user would expect to see. This would be a lot simpler than attempting to rediscover this mapping from the 3D panel positions/orientations. I realise that detectors such as the CSPAD would need handling as special cases, as the orientation of panels does not necessarily correspond to their location and orientation within the underlying raw image array.

**Comment by graeme-winter** [comment]
FWIW with Jungfrau detectors the panels are also written out in a non-obvious order

**Comment by dagewa** [comment]
That has to be set by the format class using `set_raw_image_offset` and as far as I can tell it doesn't account for gaps between modules that are not part of the array though. So, it works for DLS, true, but is not a general solution.

**Comment by dagewa** [comment]
I'm browsing old issues, and think this one can be closed as #224 provides the solution.
