### ISSUE TITLE
ADSC 422 has moved in its life

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#170]
From @jmholton in response to 1004a79c03354d2de0a419eec5868cbbac6f2aa5 - 

"Looking at the commit you just made: I'm not sure DETECTOR_SN=422 is the right way to do this.  The reason is that SN422 moved to ALS 5.0.1 on May 14 2007.  It's new owner (BCSB) changed the beam center convention listed under BEAM_CENTER_[XY]= to be the mosflm/denzo rather than the ADXV/DPS convention.  This wasn't my decision.  So, I believe your latest commit has broken processing of ALS 5.0.1 data from May 2007 forward."

"The real "key" here is DENZO_X_BEAM=. "

I note that this key is sometimes DENZO_XBEAM but even so...

Three options - 
- add a timestamp switch to the format class
- look for `DENZO_` in header keys
- look for `BEAMLINE=` in header keys

Aside: has also lived on a 2-theta stage which was used from time to time.

Will demo how to do these things as a "dxtbx howto"

**Comment by dagewa** [comment]
This looks to be complete
