### ISSUE TITLE
In DataBlockTemplateImporter allow for option to work around missing images

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#18]
i.e. if I have a sequence of images 

```
th_8_2_0310.cbf
th_8_2_0311.cbf
th_8_2_0312.cbf
th_8_2_0313.cbf
th_8_2_0314.cbf
th_8_2_0316.cbf
th_8_2_0317.cbf
th_8_2_0318.cbf
th_8_2_0319.cbf
```

let the caller have the option of dealing with this. Use case is where caller will subsequently be trimming the sweep anyway. Yes, could work around this by calculating a full list of images and trimming to what is wanted, but seems like a useful option.

**Comment by dagewa** [comment]
I think there's agreement to close this
