### ISSUE TITLE
Add concept of maximum possible pixel value

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#194]
In contrast to the idea of a maximum trusted pixel value, which is dependent on e.g. count rate limits and so on, this is simply the largest pixel value which is possible with this container format - a 16 bit TIFF would therefore have `0xffff` and an Eiger would expose the underlying HDF5 data format, modulo handling for masked values.

**Comment by graeme-winter** [comment]
Proposed API design: get maximum possible pixel value: will return format defined value if available else trusted[1] - recognising that the definition of this is itself ambiguous #182

**Comment by graeme-winter** [comment]
Probably this needs to go into the `panel` struct as a property with the default value 0 say, which can act as a guard value. If `maximum_pixel_ == 0` return trusted.

**Comment by graeme-winter** [comment]
Why do I want this?

 - to be able to search for pixels above a trusted value I would like to know what the maximum possible value is
 - to allow faithful transcoding of the data from one format to another, need to know what the maximum possible value in the file is likely to be before creating a target data set

**Comment by dagewa** [comment]
I don't really understand the reasoning.

1. Why do you need to know what the maximum possible value is in order to search for pixels above a trusted value?
2. When transcoding, you should be able to read the type of the raw array in dataset A to know if its maximum value is possible in format B.

I don't see why we have to carry around more metadata for things that AFAICT can be discoverable at the point at which you need them.

**Comment by graeme-winter** [comment]
> 1. Why do you need to know what the maximum possible value is in order to search for pixels above a trusted value?

Because you have to set _some_ value to treat as a maximum, and if you set e.g. > 65536 for 16 bit you expose a lot of weirdness

> 2. When transcoding, you should be able to read the type of the raw array in dataset A to know if its maximum value is possible in format B.

_possible_ is fine, but if you have 16 bit raw data you lose this information once you have it as a flex array so you would have to assume it was a int32 or similar.

**Comment by graeme-winter** [comment]
FWIW 1 above is the driver here.

**Comment by dagewa** [comment]
2 makes sense, but I still fail to see why you need to set a maximum value when you are trying to search for pixels above a trusted value. Why is it not just `pixels > trusted_range[1]`?

**Comment by dagewa** [comment]
BTW my main concern is avoiding the situation where this metadata might actually be a lie. As long as this _cannot_ get out of step with what's actually in the data array then it seems safe

**Comment by graeme-winter** [comment]
Because _spot finding_ does not work sensibly if you have masked pixels with value 0xffff say - it causes crazy spot finding results. This is easy to reproduce and destroys the output.

**Comment by graeme-winter** [comment]
> BTW my main concern is avoiding the situation where this metadata might actually be a lie. As long as this _cannot_ get out of step with what's actually in the data array then it seems safe

Humbly ask: how else could I get this information?

At the moment I have no way to propagate the information from a format class where I may know it to xia2 were I want it. I could break the abstraction and go delving in I guess? The default is to say that it is the `trusted_value[1]` which is a good default for CCD as it typically corresponds to the overload value. 

There is no way that I can guarantee that the metadata is THE TRUTH in as much as I have no way of ensuring that other metadata values are true, only that they are there.

**Comment by dagewa** [comment]
What worries me is that there are formats where the storage type is described using metadata in the file, and adding a free attribute that also carries this information might allow you to get out of step. Format writers may have to remember to set this attribute when they choose between `read_uint8`, `read_unit16` or whatever. All I want is, say, a check enforced during `get_raw_data` that ensures the maximum pixel value is valid

**Comment by graeme-winter** [comment]
Rather than simply asserting this, I will demonstrate in a moment. 

With this data:

/dls/i03/data/2020/mx23694-44/TestInsulin/Ins_16/Ins_16_3_master.h5 - 150 image Eiger 16M data set from diamond

```
cs04r-sc-com99-01 boom :) $ dials.find_spots nproc=20 imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.0.3-g8d758451f-release-hotfix-534f6334
The following parameters have been modified:

spotfinder {
  mp {
    nproc = 20
  }
}
input {
  experiments = imported.expt
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 1 to 150...
Setting chunksize=8
Extracting strong pixels from images
 Using multiprocessing with 20 parallel job(s)

Found 77 strong pixels on image 1
Found 81 strong pixels on image 2
Found 74 strong pixels on image 3
-----8<----
Found 54 strong pixels on image 146
Found 53 strong pixels on image 147
Found 66 strong pixels on image 148
Found 44 strong pixels on image 149
Found 50 strong pixels on image 150

Extracted 1887 spots
Removed 759 spots with size < 3 pixels
Removed 0 spots with size > 1000 pixels
Calculated 1128 spot centroids
Calculated 1128 spot intensities
Filtered 1123 of 1128 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
1123 spots found on 150 images (max 34 / bin)
*                                                           
*                                                  *        
*                                              *   *        
*        *     *            *      *    *   *  *   * *      
*  *  * **  *  *** ****    *****   *   ***  ** * * * *   ***
* ** *****  ****** ****** ******* ***  ******* *** *** *****
************************************** ******* *************
********************************************** *************
************************************************************
************************************************************
1                         image                          150

--------------------------------------------------------------------------------
Saved 1123 reflections to strong.refl
```

Then set `maximum_trusted_value=80000` which is a few more than possible to store:

```
cs04r-sc-com99-01 boom :) $ dials.find_spots nproc=20 imported.expt maximum_trusted_value=80000
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.0.3-g8d758451f-release-hotfix-534f6334
The following parameters have been modified:

maximum_trusted_value = 80000
spotfinder {
  mp {
    nproc = 20
  }
}
input {
  experiments = imported.expt
}

Overriding maximum trusted value to 80000.0
Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 1 to 150...
Setting chunksize=8
Extracting strong pixels from images
 Using multiprocessing with 20 parallel job(s)

Found 84608 strong pixels on image 1
Found 84612 strong pixels on image 2
Found 84604 strong pixels on image 3
----8<----
Found 84595 strong pixels on image 147
Found 84585 strong pixels on image 148
Found 84573 strong pixels on image 149
Found 84568 strong pixels on image 150

Extracted 7378 spots
Removed 4251 spots with size < 3 pixels
Removed 42 spots with size > 1000 pixels
Calculated 3085 spot centroids
Calculated 3085 spot intensities
Filtered 1113 of 3085 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
1113 spots found on 150 images (max 34 / bin)
*                                                           
*                                                           
*              *                               *   *        
*        *     *            *      *    *      *   *        
*  *  * **  ** *** ****   **** *   **  **** *  * * * *  ****
*  * *****  ** *** ****** ******* ***  ******* *** **** ****
************************* ***********  ******* *************
************************************************************
************************************************************
************************************************************
1                         image                          150

--------------------------------------------------------------------------------
Saved 1113 reflections to strong.refl
```

Here it was lucky that after making the shoeboxes it could finish - I have however had it use > 100 GB of ram and die before this (which I think is a bug but out of context here) 

Note the enormous number of signal pixels above.
