### ISSUE TITLE
FormatNexus: does not respect the chain of ~command~ dependency

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#200]
In theory a nexus file allows the detector hierarchy to be explicitly defined with various axes so that the eventual position of the detector is determined. This does not appear to be respected at this time, i.e. the fast and slow axes are not dependent on the stack of axes below them.

**Comment by phyy-nx** [comment]
Can you clarify?  The [JF16M dataset](https://zenodo.org/record/3352357) has an NXdetector group with NXmodule groups that have fast/slow_pixel_direction fields with depends_on attributes that specify the next level up in the hierarchy.  nexus.py reads the depends_on attributes of these fields to construct the detector model.

**Comment by graeme-winter** [comment]
For detector groups, yes, for single panel, nope, because it is a tangled mess of assumptions about poorly documented Eiger data sets from when they did not make proper nexus files

Contains many different ways of achieving the same objective with much overlap, but no proper respect for the file structure. Touching this likely to break many things so will tread carefully.

**Comment by phyy-nx** [comment]
👍

**Comment by graeme-winter** [comment]
Details on this:
- looks like the `offset` attributes are not being respected
- looks like this is not being applied to `fast_axis` `slow_axis` etc. as they are not passed into `construct_vector`

**Comment by graeme-winter** [comment]
OK, started to make headway on this at 

https://github.com/dials/dials_scratch/commit/689a15f7671d7f4a2fd3eba5a3e902f3a28f8d69

which is aiming at CBF files as we have a provably correct reference implementation in exactly the way we don't in NeXusLand

Should be relatively simple to transcribe the same thing over to parsing NeXus files (modulo coordinate systems).
