### ISSUE TITLE
Remove hardcoded eV conversion factors

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#204]
Instead use scitbx or scipy constants.  Files affected:

- [x] tests/model/test_spectrum.py
- [x] model/spectrum.h
- [x] format/nexus.py
- [x] format/FormatHDF5SaclaRayonix.py
- [x] format/FormatHDF5SaclaMPCCD.py
- [x] format/FormatHDF5Sacla.py
- [x] format/FormatCBFMini.py

**Comment by phyy-nx** [comment]
scipy is not listed as a requirement in dxtbx/libtbx_config, nor is it in any of the cctbx_project/libtbx/autobuild/conda_envs environments.  It is listed as a requirement in dials/libtbx_config and in the dials/.conda-envs environments.  Since dxtbx is part of the cctbx builder in the cctbx bootstrap, and since it's therefore possible to get dxtbx without dials, I'd say scipy isn't guaranteed to be available in dxtbx.  Therefore, I think we should get the constants from scitbx.

**Comment by phyy-nx** [comment]
Like this:

```from cctbx import factor_ev_angstrom```

**Comment by Anthchirp** [comment]
I would suggest
```python
from scitbx.constants import factor_ev_angstrom
```
instead, for consistency between the Python and C++ (`scitbx/constants.h`) versions.

**Comment by phyy-nx** [comment]
👍

**Comment by biochem-fan** [comment]
I think this is a good idea. Thanks for updating SACLA format classes.
