### ISSUE TITLE
Tests should probably not refer to personal data areas

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#229]
For example 

```
Grey-Area dxtbx :) [master] $ grep -R "/Users" `find . -name '*.py'`
./tests/model/test_experiment_list.py:        "/Users/rjgildea/tmp/118/Puck3_10_1_000%i.cbf.gz" % i for i in range(1, 4)
```

I am certain other examples exist, and I have been guilty of this on more than one occasion myself.

**Comment by rjgildea** [comment]
I do believe this test was added by some fella named @graeme-winter:
https://github.com/cctbx/dxtbx/commit/1b793ec7a9080706085a415b6d2ae69feb2fbc5f

**Comment by benjaminhwilliams** [comment]
See also dials/data-files#13.
