### ISSUE TITLE
Drop cbflib_adaptbx dependency

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#264]
With #238 out the way we can now consider dropping the `cbflib_adaptbx` dependency, which would be good news for Windows builds.

@bkpoon [pointed out](https://github.com/conda-forge/cctbx-base-feedstock/issues/4#issuecomment-727748436):
> Also, the `SConscript` for `dxtbx` has a reference to `env_etc.cbflib_common_includes`. That variable should be removed if `dxtbx` no longer depends on `cbflib_adaptbx`. Otherwise, there will be an error since that variable is defined in `cbflib_adaptbx/SConscript`.

**Comment by nksauter** [comment]
Are people aware that cbflib_adaptbx provides the support for the MarIP
(Mar Research Image Plate)?  In other words, even if the CBF support is
provided from a different source, the MarIP file reads will stop working if
cbflib_adaptbx is removed.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Catching up with this one - to be honest I would think for _DIALS_ (i.e. distinct from cctbx, labelit etc.) the intersection of users with those who use image plate detectors is pretty narrow, and I would not be surprised if it were empty. 

To be honest, I would think the focus on modern / high performance detectors for synchrotron and XFEL is a better use of our effort than supporting effectively obsolete detectors - particularly where this support makes it harder to streamline support for the vast majority of our users who are not using image plates etc. 

I recognise that this is currently tested and is depending on CBFlib, but I am minded to suggest that the cost (dropping support for this detector) is worth the benefit, particularly where it makes e.g. supporting Windows users easier (who are a surprisingly substantial amount of the user community).

**Comment by nksauter** [comment]
Despite Graeme's reasoning, this issue is not relevant to dials, it is only
about whether dxtbx will have a dependency on cbflib_adaptbx.  Labelit and
cctbx are in turn reliant on this dependency, so removing it will in turn
remove support for the legacy detector from the legacy program!

Nick
Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 847-1592

**Comment by graeme-winter** [comment]
> Despite Graeme's reasoning, this issue is not relevant to dials, it is only about whether dxtbx will have a dependency on cbflib_adaptbx. Labelit and cctbx are in turn reliant on this dependency, so removing it will in turn remove support for the legacy detector from the legacy program! 

Understood - of course yes in e.g. a PHENIX distribution you are necessarily dependent on the same CCTBX base as everything else. So we do continue to have an issue here.

**Comment by ndevenish** [comment]
As of https://github.com/cctbx/dxtbx/commit/c28cee014a489822aa8c8eedf2ef73587a3814ab, `cbflib_adaptbx` support is still present but _optional_, so this can be closed.
