### ISSUE TITLE
Scheme handling falls over on windows paths

### ISSUE THREAD

**Issue by ndevenish** [cctbx/dxtbx#283]
The registry uses the presence of a scheme to determine how to open:
https://github.com/cctbx/dxtbx/blob/dac0dbf75b823688c147b403e593b918315c00b5/format/Registry.py#L88-L89

However, on Windows:
```
>>> urlparse("c:\\a\\b\\c")
ParseResult(scheme='c', netloc='', path='\\a\\b\\c', params='', query='', fragment='')
```
(bug report [python#42215](https://bugs.python.org/issue42215), but I think the problem comes from obscure corner cases of what can validly be called a URL).

This means that windows path names don't open. I can think of two ways to solve this:
- Easiest way: Check here if the scheme matches the drive letter from `pathlib.PureWindowsPath.drive`
- More correct: Explicitly switch to `file://` URI's inside dxtbx. I looked at this a little when implementing #173, but would be a non-trivial transformation.

Minded to go with former, for now.

**Comment by Anthchirp** [comment]
going to file URIs will have implications beyond the dxtbx repository. pathlib definitely the way to go 👍 

Alternatively, couldn't we just add this trivial check?
```python
scheme = urlparse(image_file).scheme if "://" in image_file else ""
```

**Comment by ndevenish** [comment]
https://github.com/cctbx/dxtbx/commit/7c94042225acbe86f133db5aa2191b2723561d0f was my initial change:
```diff
     scheme = urlparse(image_file).scheme
+    # Check it's not A File, or A Windows Drive Path
+    if Path(image_file).is_file() or f"{scheme}:" == PureWindowsPath(image_file).drive:
+        scheme = ""
```

But actually, you are probably right that we don't need to adhere to the strictly technical (and very wide) definition of what a scheme could be
