### ISSUE TITLE
dxtbx_ext => dxtbx.__init__

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#29]
We currently
```python
from dxtbx_ext import *
```
in top level `dxtbx.__init__`

Suggest moving this to `dxtbx.ext` with a one-release grace period with deprecation warnings.

This would
* avoid polluting the `dxtbx.*` namespace, and therefore
* make clear when extension methods are used, and
* skip the automatic import of the extensions on importing dxtbx, which may not always be required

Opinions?

**Comment by ndevenish** [comment]
+1. Extension imports should only happen in their own module where they can be handled/patched. I wouldn't be surprised if there were root `dxtbx` names used that this moves, but it's better to have this separate even if we end up having to just *explicitly* import everything back into the `dxtbx` namespace.

**Comment by Anthchirp** [comment]
candidate patch added
