### ISSUE TITLE
Broken dxtbx.dlsnxs2cbf output

### ISSUE THREAD

**Issue by rjgildea** [cctbx/dxtbx#294]
```
$ dxtbx.dlsnxs2cbf $(dials.data get -q thaumatin_eiger_screen)/Therm_6_1_master.h5 out_%04d.cbf
$ dials.image_viewer out_*.cbf
```
Image 1:
![Screenshot 2021-01-29 at 16 22 34](https://user-images.githubusercontent.com/2810624/106300776-cb236e00-624e-11eb-9c72-72ebe1bfbc8c.png)
Image 2:
![Screenshot 2021-01-29 at 16 22 44](https://user-images.githubusercontent.com/2810624/106300809-d24a7c00-624e-11eb-951c-3fd1fa837171.png)
Image 3:
![Screenshot 2021-01-29 at 16 22 58](https://user-images.githubusercontent.com/2810624/106300820-d4acd600-624e-11eb-9f12-e58c7d41a9b3.png)

**Comment by rjgildea** [comment]
This appears to be working in dials v3.2 but broken in dials v3.3.

**Comment by rjgildea** [comment]
PFOB at https://github.com/cctbx/dxtbx/commit/bffa28ea73c9468d0c93c33a058822c96304ff5a

Test added in https://github.com/cctbx/dxtbx/commit/3fe313d6926b52b106aff94d9a6eb92d2664571b succeeds before this commit and fails after.

**Comment by graeme-winter** [comment]
> bffa28e

Pointy finger can reasonably point there, however I am wondering if this is pointing at some other underlying issue... investigating.

**Comment by graeme-winter** [comment]
```
-from dxtbx.ext import compress
+from dxtbx.ext import compress, uncompress
 
 
 def get_mask(nfast, nslow):
@@ -153,8 +153,10 @@ def make_cbf(in_name, template):
         if mask is None:
             mask = get_mask(width, height)
         data.as_1d().set_selected(mask.as_1d(), -1)
-
+        print(flex.sum(data))
         compressed = compress(data)
+        uncompressed = uncompress(compressed, height, width)
+        print(flex.sum(uncompressed))
```

=> 


```
Silver-Surfer dlsnxs2cbf :) $ dxtbx.dlsnxs2cbf Therm_6_1_master.h5 out_%04d.cbf
26990833
-1469196047
out_0001.cbf
27447160
1196150648
out_0002.cbf
22271214
22271214
out_0003.cbf
```

=> 🤔

**Comment by graeme-winter** [comment]
Ugh, I have a very nasty feeling about this one. 

The nasty feeling is that this change is a side-effect of changing the code optimisation level in the compiler

**Comment by Anthchirp** [comment]
CBF-free reproducer:
```python
from scitbx.array_family import flex
from dxtbx.ext import compress, uncompress

x,y=1024,128  
original = list(range(x*y))
data = flex.int(original)
compressed = compress(data)
print(f"{sum(original)=}")
uncompressed = uncompress(compressed, x, y)
print(f"{flex.sum(uncompressed)=}")   
print(f"{sum(list(uncompressed.as_1d()))=}")                                                            
```
What does `flex.sum` do? Because:
```
sum(original)=8589869056
flex.sum(uncompressed)=-65536
sum(list(uncompressed.as_1d()))=8589869056
```

**Comment by graeme-winter** [comment]
> CBF-free reproducer:
> 
> ```python
> from scitbx.array_family import flex
> from dxtbx.ext import compress, uncompress
> 
> x,y=1024,128  
> original = list(range(x*y))
> data = flex.int(original)
> compressed = compress(data)
> print(f"{sum(original)=}")
> uncompressed = uncompress(compressed, x, y)
> print(f"{flex.sum(uncompressed)=}")   
> print(f"{sum(list(uncompressed.as_1d()))=}")                                                            
> ```
> 
> What does `flex.sum` do? Because:
> 
> ```
> sum(original)=8589869056
> flex.sum(uncompressed)=-65536
> sum(list(uncompressed.as_1d()))=8589869056
> ```

Thank you

**Comment by graeme-winter** [comment]
What does `flex.sum()` to? Tries to store the number in a box which is too small:

```
>>> 2**31-1
2147483647
>>> 8589869056
8589869056
```

and, for an encore:

```
>>> numpy.int32([8589869056])
array([-65536], dtype=int32)
```

**Comment by graeme-winter** [comment]
```
from scitbx.array_family import flex
from dxtbx.ext import compress, uncompress

x,y=1024,128
original = [n % 128 for n in range(x*y)]
data = flex.int(original)
compressed = compress(data)
print(f"{sum(original)=}")
uncompressed = uncompress(compressed, x, y)
print(f"{flex.sum(uncompressed)=}")   
print(f"{flex.sum(uncompressed.as_1d())=}")   
print(f"{sum(list(uncompressed.as_1d()))=}") 
```

behaves exactly as we would _hope_

**Comment by graeme-winter** [comment]
OK, so printing the first value which does not match between the input and output of `uncompress(compress(data))` I see:

```
214 65750
```

I note that `214+2**16` is the latter number => datum.

**Comment by graeme-winter** [comment]
Additional: the _previous_ pixel value was `44369` - given that the CBF byte offset compression is to do with differences between one pixel and another I think we have something... 

Oh my

```
from scitbx.array_family import flex
from dxtbx.ext import compress, uncompress

x, y = 100, 100 

original = [1 for n in range(x*y)]

original[1000] = 44369
original[1001] = 214

data = flex.int(original)
compressed = compress(data)
print(f"{sum(original)=}")
uncompressed = uncompress(compressed, x, y)
print(f"{flex.sum(uncompressed)=}")  
```

**Comment by graeme-winter** [comment]
```
Silver-Surfer dlsnxs2cbf :) $ dials.python demo.py 
sum(original)=54581
flex.sum(uncompressed)=589813045
```

💥

**Comment by graeme-winter** [comment]
A factor

```
-    if ((-0xf777 <= delta) && (delta < 0x8000)) {
+    if ((-0x7fff <= delta) && (delta < 0x8000)) {
       s = (short)delta;
       b = ((union_short *)&s)[0].b;
```
