### ISSUE TITLE
nexus.py uses incident_wavelength incorrectly

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#31]
Our code for reading NeXus files looks at incident_wavelength and if it's array, assumes that each value corresponds to a different image:
https://github.com/dials/dxtbx/blob/master/format/nexus.py#L933-L938

However, I think we are mis-interpreting incident_wavelength:
http://download.nexusformat.org/doc/html/classes/applications/NXmx.html
"In the case of a polychromatic beam this is an array of the wavelengths with the relative weights in incident_wavelength_weight."

I have an opened an issue in NeXus about how to specify a per-shot wavelength (nexusformat/definitions#667).  In the meantime, do we have NeXus file created either for XFELs or for Eiger that use incident_wavelength as an array?

For XFELs the answer is no.  We are using mean energies and specifying only one:
https://github.com/cctbx/cctbx_project/blob/master/xfel/euxfel/agipd_cxigeom2nexus.py#L101
https://github.com/cctbx/cctbx_project/blob/master/xfel/swissfel/jf16m_cxigeom2nexus.py#L104
So for XFELs, however nexusformat/definitions#667 gets resolved, it won't affect existing files.

**Comment by graeme-winter** [comment]
In principle, data from VMXi[1] is polychromatic (i.e. pink beam from DMM) so we could in principle mock an example data set from there with some knowledge of the beam properties - I will give this a go and let you know. 

[1] https://www.diamond.ac.uk/Instruments/Mx/VMXi.html

**Comment by phyy-nx** [comment]
Pull request to update NeXus to support spectra over time is in review now: nexusformat/definitions#706

**Comment by phyy-nx** [comment]
Update, the above pull request was redone as nexusformat/definitions#717 and is now merged.  Ready to implement nexus.py to the new spec.

**Comment by dagewa** [comment]
@phyy-nx Is this still an issue, or can it be closed?

**Comment by dagewa** [comment]
I'm going to assume it can be closed (please re-open if relevant)
