### ISSUE TITLE
Format hierarchy assumption violated

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#32]
We have the assumption that any one file must only be understood by a single (leaf node) format class.

This is currently violated for `FormatCBFCspad`.

For example `dxtbx.show_matching_formats dials_regression/image_examples/LCLS_cspad_nexus/idx-20130301060858701.cbf` is matched by these formats. Arrows denote 'is-subclass-of' relation. There are two leaf nodes, `FormatCBFCspad` and `FormatCBFMultiTileStill`.

![image](https://user-images.githubusercontent.com/2102431/58587595-a8f57380-8255-11e9-9d7c-a6edbf7aa0f1.png)

I suggest to change the inheritance of `FormatCBFMultiTileHierarchyStill` from `FormatStill` to `FormatCBFMultiTileStill`.

[The test we have in place to check for these cases](https://github.com/cctbx/dxtbx/blob/f007bbcb0675e920cefe23e204d5cf6dbdea70f0/tests/test_regression_images.py#L214-L250) does not catch this. I only noticed due to refactoring work related to #26.

**Comment by graeme-winter** [comment]
This is nasty, good spot 👍

**Comment by Anthchirp** [comment]
(for record: graph made with https://graphonline.ru/en/)
