### ISSUE TITLE
DataBlockFactory broken for single images

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#336]
Regression from 1049af2839f81bf3fe05ba36b660656ab2bbdb5f and found by an [xfel regression test](https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=13210&view=logs&j=d67a088f-e2c4-5571-c38c-9d1032692245&t=b8b264dd-468e-544d-cbad-1281fd347ce2).

This code snippet reproduces the error:

```
import libtbx.load_env
import os
from dxtbx.datablock import DataBlockFactory

dials_regression = libtbx.env.find_in_repositories(relative_path="dials_regression",
                      test=os.path.isdir)

path = os.path.join(dials_regression, 'image_examples', 'LCLS_cspad_nexus', 'idx-20130301060858401.cbf')
datablocks_cbf = DataBlockFactory.from_filenames([path])
datablock_cbf = datablocks_cbf[0]
imageset_cbf = datablock_cbf.extract_imagesets()[0]
assert imageset_cbf.get_detector(0) is not None
```

Note I'm about to check in a re-write of the xfel_regression test that found the issue to use ExperimentListFactory instead of DataBlockFactory.  That will fix the current cctbx_project test failures.

Possible routes forward:
- Put above test into an xfailing test, fix the underlying problem, remove the xfailing flag
- Fully deprecate DataBlocks, obviating this issue.

**Comment by phyy-nx** [comment]
Re-write checked into xfel_regression to use ExperimentListFactory instead of DataBlockFactory ([link](https://gitlab.com/cctbx/xfel_regression/-/commit/6579b57424d171ab5fb58ca01712846b56467bc4))

**Comment by graeme-winter** [comment]
+1 for reture datablocks properly

but should probably add an xfailing tests and assess how hard to fix meantimes
