### ISSUE TITLE
in model.experiment_list.py::ExperimentListFactory should catch errors from pickle

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#358]
i.e. in 

```
    @staticmethod
    def from_serialized_format(filename, check_format=True):
        """Try to load the experiment list from a serialized format."""

        if hasattr(filename, "__fspath__"):
            filename = filename.__fspath__()  # unwrap PEP-519-style objects

        # First try as a JSON file
        try:
            return ExperimentListFactory.from_json_file(filename, check_format)
        except (FileNotFoundError, PermissionError):
            raise
        except Exception:
            pass

        # Now try as a pickle file
        return ExperimentListFactory.from_pickle_file(filename)
```

We default to pickle if _anything_ goes wrong in `from_json_file` - however there is a good chance that something bad will happen in `from_pickle_file` which we make no effort to catch -> probably bad. 

Assert - we should:
 - probe files for magic indicators of pickle, json
 - only attempt to read what we think is the right file
 - put some exception handling around pickle reading

**Comment by dagewa** [comment]
Can we remove reading of experiments from pickle entirely? Has anyone ever used this functionality?
