### ISSUE TITLE
Can we make CCTBX_INSTALL_PACKAGE_BUILD "sticky"

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#473]
Just chatting with @phyy-nx  and he came up with a niggle

Following on from... 

https://github.com/cctbx/dxtbx/pull/471

is there a way to make `CCTBX_INSTALL_PACKAGE_BUILD` sticky so that if you source the environment again _without_ having exported that you don't then find the original behaviour when `libtbx.refresh` is run. 

@phyy-nx  recognised that this was something he missed in the original discussion 😉

I guess saving this in the `dials` environment file would do the job?

**Comment by phyy-nx** [comment]
Yup, sorry I missed it :)  I have a set of example commands that might help clarify it and I'll post those later today.

**Comment by ndevenish** [comment]
Sure - ISTR that this was of some urgency to get done this week. Would early next week work for additional changes?

**Comment by phyy-nx** [comment]
Yah early next week would be just fine.

**Comment by phyy-nx** [comment]
Here's the commands I'm using to evaluate this:

```
export CCTBX_INSTALL_PACKAGE_BUILD=1
python bootstrap.py --builder=xfel --python=38 --nproc=64 base --use-conda
cp -r conda_base conda_base_original
conda activate `pwd`/conda_base
python bootstrap.py --builder=xfel --python=38 --nproc=64 build --use-conda
cd conda_base_original/
find . | sort > ../cb_orig
cd ../conda_base
find . | sort > ../cb_build
cd ../
vimdiff cb_orig cb_build
```

The diff shows some font stuff changed and an iota link changed.  Hopefully the font stuff is related to iota modifying conda_base?  Otherwise it implies it's not truly read-only yet, so there may be some more investigation needed.

I then logout and log in again, but this time leave out the environment variable and rebuild using `make reconf`:

```
cd build
source conda_setpaths.sh
make reconf
cd ..
cd conda_base
find . | sort > ../cb_makereconf
cd ..
vimdiff cb_build cb_makereconf
```

Now all the dxtbx dispatchers are present.

**Comment by phyy-nx** [comment]
Alternatively, the meaning of CCTBX_INSTALL_PACKAGE_BUILD could be reversed so the default is to not modify conda_base during the configure step?  That would move the burden of setting that environment variable to the dials bootstrap instead of the cctbx bootstrap.  Maybe something to consider?

**Comment by ndevenish** [comment]
Xia2's [equivalent](https://github.com/xia2/xia2/commit/52714416c71aef59274c3ca8f34479b8736f3023) is now in too. I think this covers the main packages causing immediate problem?

**Comment by graeme-winter** [comment]
Was necessary to revert the changes in #474 as there was a fair amount of collateral damage (xia2 ceased to work at all, amongst other things) -> backed out the changes so we can have a proper look at this when time allows.

**Comment by ndevenish** [comment]
With #511, this should now be fixed.
