### ISSUE TITLE
Mosaic crystal.change_basis returns non-mosaic crystal

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#5]
Currently MosaicCrystalSauter2014.change_basis returns a Crystal model instead of a MosaicCrystalSauter2014. Likely MosaicCrystalSauter2014 needs a proper copy constructor or change_basis needs to respect the polymorphism.

See xfailing test test_change_basis_mosaic_crystal in dxtbx/tests/model/test_crystal_model.py

**Comment by phyy-nx** [comment]
Bump.  Just hit this again in prototype code.  Assigned to me, but if anyone else wants to look at it... :D

**Comment by dwpaley** [comment]
This should have been closed by #420.
