### ISSUE TITLE
missing hdf5 dependency for the 

### ISSUE THREAD

**Issue by picca** [cctbx/dxtbx#532]
Hello while preparing a Debian package of dxtbx, I got this error.

```
debian/science-team/dxtbx/src/dxtbx/format/boost_python/image_ext.cc:21:10: fatal error: hdf5.h: Aucun fichier ou dossier de ce type
   21 | #include <hdf5.h>
      |          ^~~~~~~~
```

Indeed the hd5 dependecy is missing for this library in the cmake file

```
Python_add_library( dxtbx_format_image_ext
    MODULE
    format/boost_python/image_ext.cc
)
target_link_libraries( dxtbx_format_image_ext PUBLIC Boost::python CCTBX::scitbx )
```

you should add hdf5::hdf5

thanks for considering

Frederic

**Comment by ndevenish** [comment]
Hi Frederic,

Thanks - it seems that in all our build configurations, HDF5 is implicitly available on the system search path, so this was missed.
