### ISSUE TITLE
FullCBF trusted range

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#559]
When reviewing #536 I missed that it would affect XFEL CI test [tst_cxi_formatXTC.py](https://gitlab.com/cctbx/xfel_regression/-/blob/main/test/command_line/tst_cxi_formatXTC.py) (now disabled), but as I was looking into fixing it it sent me waaaaay down a rabbit hole.  Our current implementations of Full CBFs use conventions from older versions of ImageCIF, but newer versions have clarified overload and underload in a way that we may want to account for.  Specifically, these are differences between between version 1.5.4 and 1.8.4 (when exactly the changes were added I didn't dig into).

1. ImageCIF 1.8.4 specifies [`underload`](http://www.bernstein-plus-sons.com/software/CBF/doc/cif_img_1.8.4.html#_array_intensities.underload) as "The lowest value at which pixels for this detector are measured."  However our full CBF readers use [`undefined_value`](http://www.bernstein-plus-sons.com/software/CBF/doc/cif_img_1.8.4.html#_array_intensities.undefined_value), defined as "A value to be substituted for undefined values in the data array."  The dxtbx code is [here](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/model/detector_helpers.py#L127-L132), used [here](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/model/detector.py#L777).  Note that `underload` is not in [1.5.4](http://www.bernstein-plus-sons.com/software/CBF/doc/) so making the minimum value be the undefined value made sense when dxtbx was laid down.  However, now that we have underload we should use it in our as our trusted minimum value if available, and further it would be good to use `undefined_value` when we create masks from Full CBFs.

2. In 1.8.4, [`overload`](http://www.bernstein-plus-sons.com/software/CBF/doc/cif_img_1.8.4.html#_array_intensities.overload) is  defined as "The saturation intensity level for this data array, i.e. the value above which correct intensities may not be recorded."  Both overload and underload include this phrase: "The valid pixel values are those less than _array_intensities.overload and greater than or equal to _array_intensities.underload."  To me these sentences are contradictory, so I got word from the author @yayahjb, who told me the section should read "The saturation intensity level for this data array, i.e. the value **_at or_** above which correct intensities may not be recorded. The valid pixel values are those less than _array_intensities.overload and greater than or equal to _array_intensities.underload"

What all this means is that, taking into account #536, [`imgCIF_H`](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/model/detector.py#L777-L778) needs to change in order to match the ImageCIF spec, from

```
            underload = find_undefined_value(cbf_handle)
            overload = cbf_handle.get_overload(0)
```
to
```
            trusted_min = find_underload_value(cbf_handle) # putative new function
            if trusted_min is None: trusted_min = find_undefined_value(cbf_handle) + 1
            trusted_max = cbf_handle.get_overload(0) - 1
```
This could break a lot of stuff, to say the least.

**Comment by graeme-winter** [comment]
Abandon hope all ye who enter here

**Comment by graeme-winter** [comment]
Chatting with @phyy-nx  about this now

I note from some data from Pilatus on i19-2

```
loop_
_array_intensities.array_id
_array_intensities.binary_id
_array_intensities.linearity
_array_intensities.gain
_array_intensities.gain_esd
_array_intensities.overload
_array_intensities.undefined_value
ARRAY1 1 linear 1.0 . 118028 -1
```

**Comment by graeme-winter** [comment]
Oh 🤬

This could be _a problem_

**Comment by graeme-winter** [comment]
![Screenshot 2022-09-23 at 16 15 31](https://user-images.githubusercontent.com/1241716/191994718-e55f7135-6131-4527-806e-f9ed4b55c903.png)

Looks like less of a problem because in my case it is masked

**Comment by graeme-winter** [comment]
Suggest add PR to clarify definitions tp imgCIF dictionary to 

https://github.com/COMCIFS/imgCIF/blob/master/cif_img.dic

**Comment by graeme-winter** [comment]
_Then_ suggest here at Diamond we modify the file writing to also add an underload value to be exactly 0

**Comment by graeme-winter** [comment]
Aha! Mask above exists because

```
def determine_pilatus_mask(xdetector):
    """Return an appropriate pixel mask for a Pilatus detector."""

    size = xdetector[0].get_image_size()

    # Hardcoded module size and gap size
    detector = _DetectorDatabase["Pilatus"]

    # Edge dead areas not included, only gaps between modules matter
    n_fast, remainder = divmod(size[0], detector.module_size_fast)
    assert (n_fast - 1) * detector.gap_fast == remainder

    n_slow, remainder = divmod(size[1], detector.module_size_slow)
    assert (n_slow - 1) * detector.gap_slow == remainder

    # Specify the dead areas between the modules, i.e. the rows and columns
    # where there are no active pixels
    mask = []
    for i_fast in range(n_fast - 1):
        mask.append(
            [
                (i_fast + 1) * detector.module_size_fast
                + i_fast * detector.gap_fast
                + 1,
                (i_fast + 1) * detector.module_size_fast
                + i_fast * detector.gap_fast
                + detector.gap_fast,
                1,
                size[1],
            ]
        )
    for i_slow in range(n_slow - 1):
        mask.append(
            [
                1,
                size[0],
                (i_slow + 1) * detector.module_size_slow
                + i_slow * detector.gap_slow
                + 1,
                (i_slow + 1) * detector.module_size_slow
                + i_slow * detector.gap_slow
                + detector.gap_slow,
            ]
        )

    return mask

```

**Comment by phyy-nx** [comment]
> _Then_ suggest here at Diamond we modify the file writing to also add an underload value to be exactly 0

Agree, and considering the same for writing images in cbf_writer.py

**Comment by graeme-winter** [comment]
![Screenshot 2022-09-23 at 16 26 26](https://user-images.githubusercontent.com/1241716/191996920-0fe7c87f-b08a-4c45-939c-19d10f1396ee.png)

Data are being correctly masked (still) because of the explicit pixel mask

**Comment by phyy-nx** [comment]
Searching shows that function used in these format classes:
FormatCBFMiniPilatus.py
FormatCBFMiniADSCHF4M.py
FormatCBFFullPilatus.py
Presumably anything derived from those classes.  So anything else deriving from FormatCBFFull will be affected.

**Comment by graeme-winter** [comment]
Propose:
- patch imgCIF dictionary
- add putative function to fetch it
- fail gracefully as suggested by @phyy-nx 
- GW add to Diamond imgCIF templates

**Comment by graeme-winter** [comment]
TODO check this with data from Bruker imgCIF format

**Comment by phyy-nx** [comment]
Also, CBF writers should continue to write undefined_value as before, adding underload, to no disrupt other software suites.
