### ISSUE TITLE
Beam model should state probe type

### ISSUE THREAD

**Issue by dagewa** [cctbx/dxtbx#575]
Spotted while processing some electron diffraction data where the detector material and thickness was specified:

```
$ dials.show integrated.refl | grep "qe"
| qe                         | 0.009                              | 0.009                              | 0.009                              |
```

The QE correction is assuming 200 keV photons in this case and thus multiplying up all the intensities by about 100. In truth, these are electrons and are all easily stopped in the detector. So, the QE correction at least needs to know the probe type so we can either switch it off or do something cleverer here.

The first step then is to make `Beam` models aware of X-rays, electrons and neutrons...

**Comment by graeme-winter** [comment]
https://manual.nexusformat.org/classes/base_classes/NXsource.html

The choice of the name `probe` is perhaps questionable for those of us of a certain age with a fondness for anarchic artoons, but it is the _de facto_ standard.
