### ISSUE TITLE
treat images in local time or UTC?

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#60]
While working on https://github.com/cctbx/dxtbx/commit/cfb6cc4929f9d53b05fd29d6765344ba07bd0b31 I noticed that `FormatSMVRigakuSaturn` uses `calendar.timegm` while `FormatSMVNOIR`, `FormatSMVRigakuEiger` and `FormatSMVRigakuPilatus` use `time.mktime`.

[The former expects UTC, the latter local time.](https://stackoverflow.com/a/2956997) 

Was this a conscious choice or is this more of a cargo cult thing and nobody really knows why one was picked over the other?

current `grep timegm\|mktime`:
```python
FormatCBFMiniADSCHF4M.py:            return calendar.timegm(struct_time)
FormatSMVJHSim.py:                epoch = calendar.timegm(time.strptime(date_str, format_string))
FormatPYmultitile.py:from calendar import timegm
FormatPYmultitile.py:        epoch = timegm(strptime(str_min, "%Y-%m-%dT%H:%M%Z")) + float(str_sec)
FormatCBFMiniPilatusHelpers.py:            return calendar.timegm(struct_time) + float("0." + milliseconds)
FormatSMVADSC.py:                epoch = calendar.timegm(time.strptime(date_str, format_string))
doc/adding_new_formats.txt:            epoch = time.mktime(time.strptime(self._header_dictionary[
FormatSMVCMOS1.py:        epoch = calendar.timegm(time.strptime(date_record, "%a %b %d %Y %H:%M:%S"))
FormatTIFFRayonix.py:        epoch = time.mktime(self._get_rayonix_timestamp())
FormatRAXIS.py:        epoch = calendar.timegm(datetime.datetime(y, m, d, 0, 0, 0).timetuple())
FormatTIFFBruker.py:        epoch = time.mktime(self._get_bruker_timestamp())
FormatSMVTimePix_SU.py:                epoch = calendar.timegm(time.strptime(date_str, format_string))
FormatCBFMiniPilatusDLS12M.py:        # calendar.timegm(time.strptime('2016-04-01T00:00:00', '%Y-%m-%dT%H:%M:%S'))
FormatRAXISIVSpring8.py:        epoch = calendar.timegm(datetime.datetime(y, m, d, 0, 0, 0).timetuple())
FormatSMVRigaku.py:            epoch = time.mktime(epoch_time_struct)
FormatSMVRigaku.py:            epoch = calendar.timegm(epoch_time_struct)
```

**Comment by graeme-winter** [comment]
Humbly suggest a git blame will show clustering

**Comment by graeme-winter** [comment]
We should probably be consistent at using UTC though in almost every case it will not matter at all since we only really use time _differences_ in analysis.

That said sometimes UTC will be impossible as time does not include time zone, so in that case fall back to "local time" without worrying hard about what that means.

**Comment by Anthchirp** [comment]
yeah, can think about if it ever becomes relevant
