### ISSUE TITLE
Rigaku Saturn format assumes single-axis diffractometer even when that is false

### ISSUE THREAD

**Issue by jamesrhester** [cctbx/dxtbx#616]
Currently the `FormatSMVRigakuSaturn` format assumes a single-axis diffractometer regardless of the contents of the header. This leads to incorrect results when one of the ignored axes in a two or three circle diffractometer is set to a different value in a multi-scan situation. An example dataset would be [PDB 8egl](https://proteindiffraction.org/project/PsaeA_01463_a_AE1-ADP-GMP_8egl/).

I propose to improve the situation by changing `FormatSMVRigakuSaturn.py` to count the number of crystal gonio names defined by the header, and constructing the goniometer accordingly (as in `FormatSMVRigakuEiger`).

As a first time contributor, am I right in assuming a pull request on this repo is the appropriate way to contribute?

**Comment by graeme-winter** [comment]
> Currently the `FormatSMVRigakuSaturn` format assumes a single-axis diffractometer regardless of the contents of the header. This leads to incorrect results when one of the ignored axes in a two or three circle diffractometer is set to a different value in a multi-scan situation. An example dataset would be [PDB 8egl](https://proteindiffraction.org/project/PsaeA_01463_a_AE1-ADP-GMP_8egl/).

We've probably did not have an example set to develop against - also I think the support for Saturn may have come from Diamond i19 rather than a lab source in the first instance... so may be non-canonical.

> 
> I propose to improve the situation by changing `FormatSMVRigakuSaturn.py` to count the number of crystal gonio names defined by the header, and constructing the goniometer accordingly (as in `FormatSMVRigakuEiger`).

Very sensible

> 
> As a first time contributor, am I right in assuming a pull request on this repo is the appropriate way to contribute?

That would be much appreciated. As a veteran contributor this is also what I would so.

Am happy to be assigned as reviewer.

**Comment by jamesrhester** [comment]
Great, I have installed the dials development environment and will prepare a PR.

**Comment by graeme-winter** [comment]
If you stub your toe on something please feel free to reach out. There are plenty of idiosyncrasies in how things in `dials/dxtbx` work.

Good hunting!
