### ISSUE TITLE
Wrong geometry from FullCBFs from Bruker D8 Venture

### ISSUE THREAD

**Issue by dagewa** [cctbx/dxtbx#635]
I have lysozyme datasets from @stranskj recorded on a Bruker D8 Venture diffractometer with a Photon III M28 detector. Here are the first 10 images of one dataset (an omega scan) in either SFRM format, or FullCBF, as output by the Proteum software.

[sfrm-version.zip](https://github.com/cctbx/dxtbx/files/11479733/sfrm-version.zip)
[cbf-version.zip](https://github.com/cctbx/dxtbx/files/11479737/cbf-version.zip)

The SFRM version is imported by `FormatBrukerPhotonII`. The panel gain is not correct (set on import with `panel.gain=25` to get it approximately right) but the geometry looks correct (at least, the lysozyme cell can be indexed).

The geometry of the version imported by `FormatCBFFullByteOffset` is not interpreted correctly. It is not yet clear why.

SFRM on the left, CBF on the right:

![image](https://github.com/cctbx/dxtbx/assets/11502083/ae8e1919-e473-42ae-8c31-b7bf13a9242c)

**Comment by graeme-winter** [comment]
I think I have encountered problems with the Bruker CBF format in the past, as it was not correct ISTR? As in the metadata were not right. I will dig through my emails.

**Comment by dagewa** [comment]
After discussion with Bruker, we believe these issues are resolved for CBFs prepared with Proteum 2022.10-0 or newer.
