### ISSUE TITLE
[3.17] seems incompatible with Python 3.12

### ISSUE THREAD

**Issue by picca** [cctbx/dxtbx#677]
Hello, while preparing the Debian package (Python 3.11 and 3.12)

I get this error message during the unit test, I can reproduce this with this simple import

```
Python 3.12.1 (main, Dec  8 2023, 16:20:54) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dxtbx
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 285, in __getitem__
    return next(iter(self.select(name=name)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dxtbx/__init__.py", line 10, in <module>
    import dxtbx.format.Registry
  File "/usr/lib/python3/dist-packages/dxtbx/format/Registry.py", line 69, in <module>
    _format_dag: dict[str, list[str]] = get_format_class_dag()
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dxtbx/format/Registry.py", line 56, in get_format_class_dag
    name: class_info[1] for name, class_info in get_format_class_index().items()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dxtbx/format/Registry.py", line 37, in get_format_class_index
    for e in importlib.metadata.entry_points()["dxtbx.format"]:
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 287, in __getitem__
    raise KeyError(name)
KeyError: 'dxtbx.format'
```

Cheers

**Comment by picca** [comment]
Just for info Python3.11 is working

```
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dxtbx
>>> 
```

**Comment by ndevenish** [comment]
This looks like you are running into a very similar problem to when **you** saw this before https://github.com/cctbx/dxtbx/issues/553, as in, it looks like **you** have not registered the entry points correctly. Dxtbx looks up the registered formats at runtime, and this registration is done as part of a normal install.

Once again, we are happy to help with supported platforms or with actual design problems preventing your packaging work. However conda-forge cctbx and wxpython do not seem to support python 3.12 yet, so we can not support python 3.12 currently in dials/dxtbx.

**Comment by picca** [comment]
I investgated a bit and this is a real incompatibility with the importlib.metadata of Python3.12

https://docs.python.org/3/library/importlib.metadata.html#entry-points

now entry_points return an EntryPoints object instead of a Dictionnary.

for information, I am testing dxtbx once installed not during the build process :), to avoid the previous  issue.

thanks

Fred

Could you reopen this bug ?

**Comment by picca** [comment]
Is it possible to reopen this bug, if you considere thaht this is a real issue.

thanks
