### ISSUE TITLE
Isn't a triangle a polygon in masking?

### ISSUE THREAD

**Issue by biochem-fan** [cctbx/dxtbx#757]
Our polygon masking code rejects polygons with 3 or less vertices.

https://github.com/cctbx/dxtbx/blob/9e2674712261458c7828cf873d4582361e6c8165/src/dxtbx/masking/masking.h#L120-L122

It makes sense to reject cases with one vertex (i.e. point) or two vertices (i.e. line) but why do we reject triangles?

Changing this to

```cpp
DXTBX_ASSERT(polygon.size() >= 3); 
```

seems working but am I missing some corner cases?

**Comment by dagewa** [comment]
Perhaps this was always meant to be `>=`? I can't think of any reason to reject a triangle

**Comment by biochem-fan** [comment]
@dagewa Thanks for confirmation. I made a pull request.
