### ISSUE TITLE
Max IV Eiger work - vertical axis, to work nicely with dxtbx

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#9]
See e.g. https://github.com/cctbx/cctbx_project/commit/66a61bad32a054d0a7c52b4fe3237b3a04406967 and conversation, ongoing work

**Comment by dagewa** [comment]
I see https://github.com/cctbx/dxtbx/blob/efe7c26d9143ce6e27154d5651d61273b60b2e08/src/dxtbx/format/FormatHDF5EigerNearlyNexus.py#L267-L271

so will assume this is complete
