### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/dxtbx#95]
Hi, moving this to an issue.  @dermen and I found a dead url linked to from this line:
https://github.com/cctbx/dxtbx/blob/master/model/crystal.h#L306

Dead url:
http://goo.gl/H3p1s

Appears to redirect to
http://www-bio3d-igbmc.u-strasbg.fr/~mgsb/biophys/rx/biblio/19_06_cowtan_coordinate_frames.pdf

Looks like it should be:
https://www.iucr.org/__data/assets/pdf_file/0009/7011/19_06_cowtan_coordinate_frames.pdf

Should we copy this pdf somewhere and ensure it's hosted nicely?  Looks like a private location on IUCr.

@dagewa suggests hosting it on a CCP4 site.

**Comment by dagewa** [comment]
After a bit of detective work I found it linked to from here: https://www.iucr.org/resources/commissions/computing/schools/siena-2005-crystallographic-computing-school/speakers-notes

So I don't think the IUCr URL is supposed to be hidden after all.
